export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_FAILURE = "GET_CART_DATA_FAILURE";
export const QUANTITY_CHANGE_SUCCESS = "QUANTITY_CHANGE_SUCCESS";
export const CART_PAGE_TOTAL_AMOUNT = "CART_PAGE_TOTAL_AMOUNT";
export const CART_PAGE_TOTAL_ITEMS = "CART_PAGE_TOTAL_ITEMS";
export const APPLY_COUPON_DISCOUNT = "APPLY_COUPON_DISCOUNT";
export const APPLY_GIFTCARD = "APPLY_GIFTCARD";


